/*
WhatsApp API

API for managing WhatsApp devices and interactions

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetContactDetails200Response struct for GetContactDetails200Response
type GetContactDetails200Response struct {
	// Name of the contact
	ContactName *string `json:"contactName,omitempty"`
	// Phone number of the contact
	PhoneNumber *string `json:"phoneNumber,omitempty"`
}

// NewGetContactDetails200Response instantiates a new GetContactDetails200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetContactDetails200Response() *GetContactDetails200Response {
	this := GetContactDetails200Response{}
	return &this
}

// NewGetContactDetails200ResponseWithDefaults instantiates a new GetContactDetails200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetContactDetails200ResponseWithDefaults() *GetContactDetails200Response {
	this := GetContactDetails200Response{}
	return &this
}

// GetContactName returns the ContactName field value if set, zero value otherwise.
func (o *GetContactDetails200Response) GetContactName() string {
	if o == nil || o.ContactName == nil {
		var ret string
		return ret
	}
	return *o.ContactName
}

// GetContactNameOk returns a tuple with the ContactName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetContactDetails200Response) GetContactNameOk() (*string, bool) {
	if o == nil || o.ContactName == nil {
		return nil, false
	}
	return o.ContactName, true
}

// HasContactName returns a boolean if a field has been set.
func (o *GetContactDetails200Response) HasContactName() bool {
	if o != nil && o.ContactName != nil {
		return true
	}

	return false
}

// SetContactName gets a reference to the given string and assigns it to the ContactName field.
func (o *GetContactDetails200Response) SetContactName(v string) {
	o.ContactName = &v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise.
func (o *GetContactDetails200Response) GetPhoneNumber() string {
	if o == nil || o.PhoneNumber == nil {
		var ret string
		return ret
	}
	return *o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetContactDetails200Response) GetPhoneNumberOk() (*string, bool) {
	if o == nil || o.PhoneNumber == nil {
		return nil, false
	}
	return o.PhoneNumber, true
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *GetContactDetails200Response) HasPhoneNumber() bool {
	if o != nil && o.PhoneNumber != nil {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given string and assigns it to the PhoneNumber field.
func (o *GetContactDetails200Response) SetPhoneNumber(v string) {
	o.PhoneNumber = &v
}

func (o GetContactDetails200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ContactName != nil {
		toSerialize["contactName"] = o.ContactName
	}
	if o.PhoneNumber != nil {
		toSerialize["phoneNumber"] = o.PhoneNumber
	}
	return json.Marshal(toSerialize)
}

type NullableGetContactDetails200Response struct {
	value *GetContactDetails200Response
	isSet bool
}

func (v NullableGetContactDetails200Response) Get() *GetContactDetails200Response {
	return v.value
}

func (v *NullableGetContactDetails200Response) Set(val *GetContactDetails200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetContactDetails200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetContactDetails200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetContactDetails200Response(val *GetContactDetails200Response) *NullableGetContactDetails200Response {
	return &NullableGetContactDetails200Response{value: val, isSet: true}
}

func (v NullableGetContactDetails200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetContactDetails200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


