/*
WhatsApp API

API for managing WhatsApp devices and interactions

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetJoinedGroups200ResponseInner struct for GetJoinedGroups200ResponseInner
type GetJoinedGroups200ResponseInner struct {
	// ID of the group
	GroupId *string `json:"groupId,omitempty"`
	// Name of the group
	GroupName *string `json:"groupName,omitempty"`
}

// NewGetJoinedGroups200ResponseInner instantiates a new GetJoinedGroups200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetJoinedGroups200ResponseInner() *GetJoinedGroups200ResponseInner {
	this := GetJoinedGroups200ResponseInner{}
	return &this
}

// NewGetJoinedGroups200ResponseInnerWithDefaults instantiates a new GetJoinedGroups200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetJoinedGroups200ResponseInnerWithDefaults() *GetJoinedGroups200ResponseInner {
	this := GetJoinedGroups200ResponseInner{}
	return &this
}

// GetGroupId returns the GroupId field value if set, zero value otherwise.
func (o *GetJoinedGroups200ResponseInner) GetGroupId() string {
	if o == nil || o.GroupId == nil {
		var ret string
		return ret
	}
	return *o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetJoinedGroups200ResponseInner) GetGroupIdOk() (*string, bool) {
	if o == nil || o.GroupId == nil {
		return nil, false
	}
	return o.GroupId, true
}

// HasGroupId returns a boolean if a field has been set.
func (o *GetJoinedGroups200ResponseInner) HasGroupId() bool {
	if o != nil && o.GroupId != nil {
		return true
	}

	return false
}

// SetGroupId gets a reference to the given string and assigns it to the GroupId field.
func (o *GetJoinedGroups200ResponseInner) SetGroupId(v string) {
	o.GroupId = &v
}

// GetGroupName returns the GroupName field value if set, zero value otherwise.
func (o *GetJoinedGroups200ResponseInner) GetGroupName() string {
	if o == nil || o.GroupName == nil {
		var ret string
		return ret
	}
	return *o.GroupName
}

// GetGroupNameOk returns a tuple with the GroupName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetJoinedGroups200ResponseInner) GetGroupNameOk() (*string, bool) {
	if o == nil || o.GroupName == nil {
		return nil, false
	}
	return o.GroupName, true
}

// HasGroupName returns a boolean if a field has been set.
func (o *GetJoinedGroups200ResponseInner) HasGroupName() bool {
	if o != nil && o.GroupName != nil {
		return true
	}

	return false
}

// SetGroupName gets a reference to the given string and assigns it to the GroupName field.
func (o *GetJoinedGroups200ResponseInner) SetGroupName(v string) {
	o.GroupName = &v
}

func (o GetJoinedGroups200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.GroupId != nil {
		toSerialize["groupId"] = o.GroupId
	}
	if o.GroupName != nil {
		toSerialize["groupName"] = o.GroupName
	}
	return json.Marshal(toSerialize)
}

type NullableGetJoinedGroups200ResponseInner struct {
	value *GetJoinedGroups200ResponseInner
	isSet bool
}

func (v NullableGetJoinedGroups200ResponseInner) Get() *GetJoinedGroups200ResponseInner {
	return v.value
}

func (v *NullableGetJoinedGroups200ResponseInner) Set(val *GetJoinedGroups200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetJoinedGroups200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetJoinedGroups200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetJoinedGroups200ResponseInner(val *GetJoinedGroups200ResponseInner) *NullableGetJoinedGroups200ResponseInner {
	return &NullableGetJoinedGroups200ResponseInner{value: val, isSet: true}
}

func (v NullableGetJoinedGroups200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetJoinedGroups200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


