/*
WhatsApp API

API for managing WhatsApp devices and interactions

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetQRCodeByRefreshCode200Response struct for GetQRCodeByRefreshCode200Response
type GetQRCodeByRefreshCode200Response struct {
	// Base64-encoded QR code image
	QrCode *string `json:"qrCode,omitempty"`
}

// NewGetQRCodeByRefreshCode200Response instantiates a new GetQRCodeByRefreshCode200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetQRCodeByRefreshCode200Response() *GetQRCodeByRefreshCode200Response {
	this := GetQRCodeByRefreshCode200Response{}
	return &this
}

// NewGetQRCodeByRefreshCode200ResponseWithDefaults instantiates a new GetQRCodeByRefreshCode200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetQRCodeByRefreshCode200ResponseWithDefaults() *GetQRCodeByRefreshCode200Response {
	this := GetQRCodeByRefreshCode200Response{}
	return &this
}

// GetQrCode returns the QrCode field value if set, zero value otherwise.
func (o *GetQRCodeByRefreshCode200Response) GetQrCode() string {
	if o == nil || o.QrCode == nil {
		var ret string
		return ret
	}
	return *o.QrCode
}

// GetQrCodeOk returns a tuple with the QrCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetQRCodeByRefreshCode200Response) GetQrCodeOk() (*string, bool) {
	if o == nil || o.QrCode == nil {
		return nil, false
	}
	return o.QrCode, true
}

// HasQrCode returns a boolean if a field has been set.
func (o *GetQRCodeByRefreshCode200Response) HasQrCode() bool {
	if o != nil && o.QrCode != nil {
		return true
	}

	return false
}

// SetQrCode gets a reference to the given string and assigns it to the QrCode field.
func (o *GetQRCodeByRefreshCode200Response) SetQrCode(v string) {
	o.QrCode = &v
}

func (o GetQRCodeByRefreshCode200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.QrCode != nil {
		toSerialize["qrCode"] = o.QrCode
	}
	return json.Marshal(toSerialize)
}

type NullableGetQRCodeByRefreshCode200Response struct {
	value *GetQRCodeByRefreshCode200Response
	isSet bool
}

func (v NullableGetQRCodeByRefreshCode200Response) Get() *GetQRCodeByRefreshCode200Response {
	return v.value
}

func (v *NullableGetQRCodeByRefreshCode200Response) Set(val *GetQRCodeByRefreshCode200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetQRCodeByRefreshCode200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetQRCodeByRefreshCode200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetQRCodeByRefreshCode200Response(val *GetQRCodeByRefreshCode200Response) *NullableGetQRCodeByRefreshCode200Response {
	return &NullableGetQRCodeByRefreshCode200Response{value: val, isSet: true}
}

func (v NullableGetQRCodeByRefreshCode200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetQRCodeByRefreshCode200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


