/*
WhatsApp API

API for managing WhatsApp devices and interactions

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AddGroupMembersRequest struct for AddGroupMembersRequest
type AddGroupMembersRequest struct {
	// List of phone numbers to be added as group members
	PhoneNumbers []string `json:"phoneNumbers,omitempty"`
}

// NewAddGroupMembersRequest instantiates a new AddGroupMembersRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddGroupMembersRequest() *AddGroupMembersRequest {
	this := AddGroupMembersRequest{}
	return &this
}

// NewAddGroupMembersRequestWithDefaults instantiates a new AddGroupMembersRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddGroupMembersRequestWithDefaults() *AddGroupMembersRequest {
	this := AddGroupMembersRequest{}
	return &this
}

// GetPhoneNumbers returns the PhoneNumbers field value if set, zero value otherwise.
func (o *AddGroupMembersRequest) GetPhoneNumbers() []string {
	if o == nil || o.PhoneNumbers == nil {
		var ret []string
		return ret
	}
	return o.PhoneNumbers
}

// GetPhoneNumbersOk returns a tuple with the PhoneNumbers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddGroupMembersRequest) GetPhoneNumbersOk() ([]string, bool) {
	if o == nil || o.PhoneNumbers == nil {
		return nil, false
	}
	return o.PhoneNumbers, true
}

// HasPhoneNumbers returns a boolean if a field has been set.
func (o *AddGroupMembersRequest) HasPhoneNumbers() bool {
	if o != nil && o.PhoneNumbers != nil {
		return true
	}

	return false
}

// SetPhoneNumbers gets a reference to the given []string and assigns it to the PhoneNumbers field.
func (o *AddGroupMembersRequest) SetPhoneNumbers(v []string) {
	o.PhoneNumbers = v
}

func (o AddGroupMembersRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.PhoneNumbers != nil {
		toSerialize["phoneNumbers"] = o.PhoneNumbers
	}
	return json.Marshal(toSerialize)
}

type NullableAddGroupMembersRequest struct {
	value *AddGroupMembersRequest
	isSet bool
}

func (v NullableAddGroupMembersRequest) Get() *AddGroupMembersRequest {
	return v.value
}

func (v *NullableAddGroupMembersRequest) Set(val *AddGroupMembersRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddGroupMembersRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddGroupMembersRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddGroupMembersRequest(val *AddGroupMembersRequest) *NullableAddGroupMembersRequest {
	return &NullableAddGroupMembersRequest{value: val, isSet: true}
}

func (v NullableAddGroupMembersRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddGroupMembersRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


